export const staticUser = [
  {
    id: 1,
    firstName: 'elie',
    lastName: 'lastname1',
    email: 'elie@hotmail.com',
    password: '123',
    location: '',
  },
  {
    id: 2,
    firstName: 'user2',
    lastName: 'lastname2',
    email: 'user2@hotmail.com',
    password: '123',
    location: '',
  },
  {
    id: 3,
    firstName: 'john',
    lastName: 'doe',
    email: 'john.doe@example.com',
    password: 'password123',
    location: 'new york, USA',
  },
  {
    id: 4,
    firstName: 'alice',
    lastName: 'smith',
    email: 'alice.smith@example.com',
    password: 'qwerty456',
    location: 'los angeles, USA',
  },
  {
    id: 5,
    firstName: 'michael',
    lastName: 'johnson',
    email: 'michael.johnson@example.com',
    password: 'abc123',
    location: 'chicago, USA',
  },
  {
    id: 6,
    firstName: 'david',
    lastName: 'williams',
    email: 'david.williams@example.com',
    password: 'securepassword',
    location: 'Tripoli, Lebanon',
  },
];
